server:
  port: 9094

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://Restaurante:restaurante123@cluster0.pyjmrpz.mongodb.net/orderdb?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/