server:
  port: 8082 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: CATALOGUE-SERVICE 

  datasource:
    url: jdbc:mysql://localhost:3306/cataloguedb?createDatabaseIfNotExist=true
    password: jeol_pass
    username: jeol_user
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect