server:
  port: 8082  

spring:
  application:
    name: CATALOGUE-SERVICE  

  datasource:
    url: jdbc:h2:mem:foodcatalogue-db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/